<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-06-12T20:57:55 BST" name="Suite" finished-at="2020-06-12T20:57:55 BST" duration-ms="66">
    <groups>
      <group name="checkintest">
        <method signature="TestCheckOrder.testCheckOrder()[pri:0, instance:com.vcit.automation.TestCheckOrder@61d6015a]" name="testCheckOrder" class="com.vcit.automation.TestCheckOrder"/>
      </group> <!-- checkintest -->
      <group name="functest">
        <method signature="TestCheckOrder.testCheckOrder()[pri:0, instance:com.vcit.automation.TestCheckOrder@61d6015a]" name="testCheckOrder" class="com.vcit.automation.TestCheckOrder"/>
      </group> <!-- functest -->
    </groups>
    <test started-at="2020-06-12T20:57:55 BST" name="Test" finished-at="2020-06-12T20:57:55 BST" duration-ms="66">
      <class name="com.vcit.automation.TestCheckOrder">
        <test-method signature="testCheckOrder()[pri:0, instance:com.vcit.automation.TestCheckOrder@61d6015a]" started-at="2020-06-12T20:57:55 BST" name="testCheckOrder" finished-at="2020-06-12T20:57:55 BST" duration-ms="11" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.vcit.automation.TestCheckOrder.testCheckOrder(TestCheckOrder.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCheckOrder -->
      </class> <!-- com.vcit.automation.TestCheckOrder -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
